### ISSUE TITLE
Cannot build against cohttp 0.19.1 with ocaml 4.02.3

### ISSUE THREAD

**Issue by michipili** [mirage/ocaml-github#89]
This morning, I failed to to build  **ocaml-github** with **opam** that gave up the ghost with:

```
# + /opt/opam/4.02.3/bin/ocamlfind ocamlc -c -g -annot -bin-annot -principal -strict-sequence -package atdgen -package cohttp -package cohttp.lwt-core -package lwt -package uri -package yojson -w @5@8@10@11@12@14@23@24@26@29 -I lib -o lib/github_core.cmo lib/github_core.ml
# File "lib/github_core.ml", line 314, characters 20-33:
# Error: Unbound module CL.Response
# Command exited with code 2.
```

My wild guess is that there is a version desync with *cohttp** – its current version is 0.19.1 on my system. Any thoughts on this?

**Comment by avsm** [comment]
Are you trying to install the latest Github bindings (>=1.0.0)?  They were fixed to work with any Cohttp>=0.17.0.  Try "opam update" to get the latest.

**Comment by michipili** [comment]
Github bindings were already 1.0.0 but after upgrading cohttp from 0.19.1 to 0.19.2. github binding can be installed again. Thanks!

**Comment by avsm** [comment]
That does seem like a broken constraint then. I'll just restrict them to >=0.19.2
